activeProvider: ollama
providers:
  - id: openrouter
    displayName: OpenRouter Community
    mode: remote
    baseUrl: https://openrouter.ai/api/v1
    apiKey: "${LLM_OPENROUTER_API_KEY:}"
    model: tngtech/deepseek-r1t-chimera:free
    enabled: true
  - id: ollama
    displayName: Ollama Local
    mode: local
    baseUrl: http://localhost:11434
    # model: "codellama:7b-instruct-q4_0"
    model: "qwen3-coder:480b-cloud"
    enabled: true
